#第2章:UNIX指令

檔popular-names.txt以製表符（TAB）為分隔，存儲了美國新生兒的有關資訊（姓名，性別，人數與出生年份）。 編寫程式以完成下列處理，並將檔popular-names.txt作為輸入運行該程式。 進一步地，請確認通過執行UNIX命令也能獲得相同或類似的結果

In [11]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [12]:
%cd /content/drive/My Drive/1142TextMining/
!ls

/content/drive/My Drive/1142TextMining
10065作業2.ipynb    11.txt	     alice.zip	     col2.txt		  sampleCode.ipynb
10065作業3.ipynb    alice.txt	     build_alice.sh  enwiki-country.json  Untitled
10065_作業4.ipynb   alice.txt.conll  col12.txt	     popular-names.txt
10065_作業一.ipynb  alice.txt.json   col1.txt	     readme.alice.md

#10. 行數計算

計算檔的總行數。 使用命令確認結果

In [13]:
!wc -l ./popular-names.txt
#-l:Unix語法 l:log,-l逐行

2780 ./popular-names.txt

In [14]:
import pandas as pd
df = pd.read_csv('./popular-names.txt', sep='\t', header=None)
df.head()
df.shape

(2780, 4)

#11. 替換製表元為空格

將所有製表元替換為空格。 使用， 或命令確認結果。sedtrexpand

In [15]:
!sed -e 's/\t/ /g' ./popular-names.txt | head -n 7 #|是而且 -n 7只顯示前7行

Mary F 7065 1880
Anna F 2604 1880
Emma F 2003 1880
Elizabeth F 1939 1880
Minnie F 1746 1880
Margaret F 1578 1880
Ida F 1472 1880

#12. 第一列保存在col1.txt中，第二列保存在col2.txt中

提取每一行第一列的資訊，將其輸出並存儲為。 提取每一行第二列的資訊，將其輸出並存儲為。 使用命令確認結果。col1.txtcol2.txtcut

In [6]:
data = pd.read_csv('./popular-names.txt', sep='\t', header=None)
data.head()

           0  1     2     3
0       Mary  F  7065  1880
1       Anna  F  2604  1880
2       Emma  F  2003  1880
3  Elizabeth  F  1939  1880
4     Minnie  F  1746  1880

In [7]:
col_one=data[0]
col_one.to_csv('col1.txt', sep='\t', header=False, index=False)
col_two=data[1]
col_two.to_csv('col2.txt', sep='\t', header=False, index=False)

#13. 合併col1.txt與col2.txt

合併檔與的內容，並存儲為一個新的文本檔。 該檔中，每行包含初始檔第一列與第二列的值，列與列之間以製表符分隔。 使用命令確認結果。col1.txtcol2.txtpaste

In [8]:
colonetwo = pd.concat([col_one, col_two], axis=1)
colonetwo.to_csv('col12.txt', sep='\t', header=False, index=False)

#14. 前N行

以命令行參數等形式接收自然數N
，輸出檔前N
行的內容。 使用命令確認結果。

In [9]:
data.head(5)

           0  1     2     3
0       Mary  F  7065  1880
1       Anna  F  2604  1880
2       Emma  F  2003  1880
3  Elizabeth  F  1939  1880
4     Minnie  F  1746  1880

#15. 後N行

以命令行參數等形式接收自然數N
，輸出檔後N
行的內容。 使用命令確認結果。

In [10]:
data.tail(4)

           0  1      2     3
2776  Elijah  M  12886  2018
2777   Lucas  M  12585  2018
2778   Mason  M  12435  2018
2779   Logan  M  12352  2018

#16. 將文件分為N份

以命令行參數等形式接收自然數N
，按「行」為單位將原檔分割成N
份。 使用命令確認結果。

In [19]:
#N =2 or 3
#會用到迴圈
import math
N = 3
with open('popular-names.txt', 'r') as f:
    lines = f.readlines()
total_lines = len(lines)
lines_per_file = math.ceil(total_lines / N)
print(f"總行數: {total_lines}")
print(f"每份約: {lines_per_file} 行")
for i in range(N):
    start = i * lines_per_file
    end = start + lines_per_file
    chunk = lines[start:end]
    with open(f'part_{i+1}.txt', 'w') as f:
        f.writelines(chunk)
    print(f"part_{i+1}.txt 建立完成，共 {len(chunk)} 行")

總行數: 2780
每份約: 927 行
part_1.txt 建立完成，共 927 行
part_2.txt 建立完成，共 927 行
part_3.txt 建立完成，共 926 行

#17. 第一列中的非重複字串
列出檔第一列中所有字串的種類（即所有不重複的字串組合）。 使用， 與 命令確認結果。

In [20]:
!cut -f1 popular-names.txt | sort | uniq

Abigail
Aiden
Alexander
Alexis
Alice
Amanda
Amelia
Amy
Andrew
Angela
Anna
Annie
Anthony
Ashley
Austin
Ava
Barbara
Benjamin
Bertha
Bessie
Betty
Brandon
Brian
Brittany
Carol
Carolyn
Charles
Charlotte
Chloe
Christopher
Clara
Crystal
Cynthia
Daniel
David
Deborah
Debra
Donald
Donna
Doris
Dorothy
Edward
Elijah
Elizabeth
Emily
Emma
Ethan
Ethel
Evelyn
Florence
Frances
Frank
Gary
George
Hannah
Harper
Harry
Heather
Helen
Henry
Ida
Isabella
Jacob
James
Jason
Jayden
Jeffrey
Jennifer
Jessica
Joan
John
Joseph
Joshua
Judith
Julie
Justin
Karen
Kathleen
Kelly
Kimberly
Larry
Laura
Lauren
Liam
Lillian
Linda
Lisa
Logan
Lori
Lucas
Madison
Margaret
Marie
Mark
Mary
Mason
Matthew
Megan
Melissa
Mia
Michael
Michelle
Mildred
Minnie
Nancy
Nicholas
Nicole
Noah
Oliver
Olivia
Pamela
Patricia
Rachel
Rebecca
Richard
Robert
Ronald
Ruth
Samantha
Sandra
Sarah
Scott
Sharon
Shirley
Sophia
Stephanie
Steven
Susan
Tammy
Taylor
Thomas
Tracy
Tyler
Virginia
Walter
William

#18. 以第三列為指標對各行進行降序排序
在不改變每行內容的前提下，按第三列的數值大小對所有行降序排序。 使用命令確認結果，但程式的運行結果無需與其完全一致

In [23]:
!sort -k3,3nr popular-names.txt > sorted_by_col3.txt #-k3,3：用第3欄作為排序欄位（Tab 分隔）n：代表按數值排序 r：代表降序
!head sorted_by_col3.txt

Linda	F	99689	1947
Linda	F	96211	1948
James	M	94757	1947
Michael	M	92704	1957
Robert	M	91640	1947
Linda	F	91016	1949
Michael	M	90656	1956
Michael	M	90517	1958
James	M	88584	1948
Michael	M	88528	1954

#19. 降序排列第一列各字串的出現頻率
求各行第一列中每種字串的出現頻率，並按該頻率將其降序排列。 使用， 與 命令確認結果

In [27]:
!cut -f1 popular-names.txt | sort | uniq -c | sort -nr

    118 James
    111 William
    108 Robert
    108 John
     92 Mary
     75 Charles
     74 Michael
     73 Elizabeth
     70 Joseph
     60 Margaret
     58 Thomas
     58 George
     57 David
     51 Richard
     45 Helen
     43 Frank
     43 Christopher
     41 Anna
     40 Edward
     39 Ruth
     38 Patricia
     37 Matthew
     36 Dorothy
     35 Emma
     32 Barbara
     31 Joshua
     31 Daniel
     26 Sarah
     26 Linda
     26 Jennifer
     26 Emily
     25 Jessica
     25 Jacob
     24 Susan
     24 Mildred
     24 Betty
     23 Henry
     23 Ashley
     22 Nancy
     21 Andrew
     20 Marie
     20 Florence
     20 Donald
     20 Amanda
     19 Samantha
     18 Olivia
     18 Melissa
     18 Madison
     18 Lisa
     18 Karen
     17 Stephanie
     17 Abigail
     16 Sandra
     16 Mark
     16 Ethel
     15 Michelle
     15 Isabella
     15 Heather
     15 Frances
     15 Ethan
     15 Carol
     15 Angela
     14 Shirley
     14 Kimberly
     14 Ava
     14 Amy
     13 Virginia
     13 Sophia
     13 Nicole
     13 Jason
     13 Hannah
     13 Deborah
     13 Brian
     12 Minnie
     12 Donna
     12 Bertha
     11 Cynthia
     10 Ronald
     10 Noah
     10 Nicholas
     10 Mia
     10 Doris
     10 Brittany
     10 Alice
      9 Tyler
      9 Joan
      9 Debra
      8 Taylor
      8 Mason
      8 Judith
      8 Ida
      8 Clara
      8 Alexis
      8 Alexander
      7 Tammy
      7 Steven
      7 Sharon
      7 Liam
      7 Harry
      7 Brandon
      6 Anthony
      5 Jeffrey
      5 Jayden
      5 Gary
      5 Charlotte
      5 Annie
      4 Lillian
      4 Kathleen
      4 Justin
      4 Chloe
      4 Benjamin
      4 Austin
      3 Megan
      3 Harper
      3 Evelyn
      3 Elijah
      3 Aiden
      2 Rebecca
      2 Oliver
      2 Logan
      2 Lauren
      2 Larry
      2 Bessie
      2 Amelia
      1 Walter
      1 Tracy
      1 Scott
      1 Rachel
      1 Pamela
      1 Lucas
      1 Lori
      1 Laura
      1 Kelly
      1 Julie
      1 Crystal
      1 Carolyn